/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardsRouteImport } from './routes/dashboards'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminAccessLogsRouteImport } from './routes/admin.access-logs'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMonitoringRouteImport } from './routes/admin.monitoring'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts.$alertId'
import { Route as DashboardsDashboardIdRouteImport } from './routes/dashboards.$dashboardId'
import { Route as DatasetsIndexRouteImport } from './routes/datasets.index'
import { Route as DatasetsConnectorIdRouteImport } from './routes/datasets.$connectorId'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginForgotRouteImport } from './routes/login.forgot'
import { Route as LoginResetRouteImport } from './routes/login.reset'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as AlertsAlertIdEditRouteImport } from './routes/alerts.$alertId.edit'
import { Route as DashboardsDashboardIdEditRouteImport } from './routes/dashboards.$dashboardId.edit'
import { Route as ReportsReportIdEditRouteImport } from './routes/reports.$reportId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsRoute = DashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessLogsRoute = AdminAccessLogsRouteImport.update({
  id: '/admin/access-logs',
  path: '/admin/access-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/admin/compliance',
  path: '/admin/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/$alertId',
  path: '/$alertId',
  getParentRoute: () => AlertsRoute,
} as any)
const DashboardsDashboardIdRoute = DashboardsDashboardIdRouteImport.update({
  id: '/$dashboardId',
  path: '/$dashboardId',
  getParentRoute: () => DashboardsRoute,
} as any)
const DatasetsIndexRoute = DatasetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DatasetsRoute,
} as any)
const DatasetsConnectorIdRoute = DatasetsConnectorIdRouteImport.update({
  id: '/$connectorId',
  path: '/$connectorId',
  getParentRoute: () => DatasetsRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginForgotRoute = LoginForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => LoginRoute,
} as any)
const LoginResetRoute = LoginResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => LoginRoute,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)
const AlertsAlertIdEditRoute = AlertsAlertIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AlertsAlertIdRoute,
} as any)
const DashboardsDashboardIdEditRoute =
  DashboardsDashboardIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardsDashboardIdRoute,
  } as any)
const ReportsReportIdEditRoute = ReportsReportIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ReportsReportIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/datasets': typeof DatasetsRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/datasets/$connectorId': typeof DatasetsConnectorIdRoute
  '/login/forgot': typeof LoginForgotRoute
  '/login/reset': typeof LoginResetRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/datasets/': typeof DatasetsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/alerts/$alertId/edit': typeof AlertsAlertIdEditRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/reports/$reportId/edit': typeof ReportsReportIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/embed': typeof EmbedRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/datasets/$connectorId': typeof DatasetsConnectorIdRoute
  '/login/forgot': typeof LoginForgotRoute
  '/login/reset': typeof LoginResetRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/datasets': typeof DatasetsIndexRoute
  '/login': typeof LoginIndexRoute
  '/alerts/$alertId/edit': typeof AlertsAlertIdEditRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/reports/$reportId/edit': typeof ReportsReportIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/dashboards': typeof DashboardsRouteWithChildren
  '/datasets': typeof DatasetsRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/access-logs': typeof AdminAccessLogsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRouteWithChildren
  '/dashboards/$dashboardId': typeof DashboardsDashboardIdRouteWithChildren
  '/datasets/$connectorId': typeof DatasetsConnectorIdRoute
  '/login/forgot': typeof LoginForgotRoute
  '/login/reset': typeof LoginResetRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/datasets/': typeof DatasetsIndexRoute
  '/login/': typeof LoginIndexRoute
  '/alerts/$alertId/edit': typeof AlertsAlertIdEditRoute
  '/dashboards/$dashboardId/edit': typeof DashboardsDashboardIdEditRoute
  '/reports/$reportId/edit': typeof ReportsReportIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api-keys'
    | '/dashboard'
    | '/dashboards'
    | '/datasets'
    | '/embed'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/access-logs'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/compliance'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/support'
    | '/admin/tenants'
    | '/alerts/$alertId'
    | '/dashboards/$dashboardId'
    | '/datasets/$connectorId'
    | '/login/forgot'
    | '/login/reset'
    | '/reports/$reportId'
    | '/datasets/'
    | '/login/'
    | '/alerts/$alertId/edit'
    | '/dashboards/$dashboardId/edit'
    | '/reports/$reportId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api-keys'
    | '/dashboard'
    | '/dashboards'
    | '/embed'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/access-logs'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/compliance'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/support'
    | '/admin/tenants'
    | '/alerts/$alertId'
    | '/dashboards/$dashboardId'
    | '/datasets/$connectorId'
    | '/login/forgot'
    | '/login/reset'
    | '/reports/$reportId'
    | '/datasets'
    | '/login'
    | '/alerts/$alertId/edit'
    | '/dashboards/$dashboardId/edit'
    | '/reports/$reportId/edit'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/api-keys'
    | '/dashboard'
    | '/dashboards'
    | '/datasets'
    | '/embed'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/admin/access-logs'
    | '/admin/admins'
    | '/admin/audit-logs'
    | '/admin/compliance'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/monitoring'
    | '/admin/roles'
    | '/admin/support'
    | '/admin/tenants'
    | '/alerts/$alertId'
    | '/dashboards/$dashboardId'
    | '/datasets/$connectorId'
    | '/login/forgot'
    | '/login/reset'
    | '/reports/$reportId'
    | '/datasets/'
    | '/login/'
    | '/alerts/$alertId/edit'
    | '/dashboards/$dashboardId/edit'
    | '/reports/$reportId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DashboardRoute: typeof DashboardRoute
  DashboardsRoute: typeof DashboardsRouteWithChildren
  DatasetsRoute: typeof DatasetsRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  LoginRoute: typeof LoginRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AdminAccessLogsRoute: typeof AdminAccessLogsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards': {
      id: '/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof DashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access-logs': {
      id: '/admin/access-logs'
      path: '/admin/access-logs'
      fullPath: '/admin/access-logs'
      preLoaderRoute: typeof AdminAccessLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/admin/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof AlertsRoute
    }
    '/dashboards/$dashboardId': {
      id: '/dashboards/$dashboardId'
      path: '/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof DashboardsDashboardIdRouteImport
      parentRoute: typeof DashboardsRoute
    }
    '/datasets/': {
      id: '/datasets/'
      path: '/'
      fullPath: '/datasets/'
      preLoaderRoute: typeof DatasetsIndexRouteImport
      parentRoute: typeof DatasetsRoute
    }
    '/datasets/$connectorId': {
      id: '/datasets/$connectorId'
      path: '/$connectorId'
      fullPath: '/datasets/$connectorId'
      preLoaderRoute: typeof DatasetsConnectorIdRouteImport
      parentRoute: typeof DatasetsRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/forgot': {
      id: '/login/forgot'
      path: '/forgot'
      fullPath: '/login/forgot'
      preLoaderRoute: typeof LoginForgotRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/reset': {
      id: '/login/reset'
      path: '/reset'
      fullPath: '/login/reset'
      preLoaderRoute: typeof LoginResetRouteImport
      parentRoute: typeof LoginRoute
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/alerts/$alertId/edit': {
      id: '/alerts/$alertId/edit'
      path: '/edit'
      fullPath: '/alerts/$alertId/edit'
      preLoaderRoute: typeof AlertsAlertIdEditRouteImport
      parentRoute: typeof AlertsAlertIdRoute
    }
    '/dashboards/$dashboardId/edit': {
      id: '/dashboards/$dashboardId/edit'
      path: '/edit'
      fullPath: '/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof DashboardsDashboardIdEditRouteImport
      parentRoute: typeof DashboardsDashboardIdRoute
    }
    '/reports/$reportId/edit': {
      id: '/reports/$reportId/edit'
      path: '/edit'
      fullPath: '/reports/$reportId/edit'
      preLoaderRoute: typeof ReportsReportIdEditRouteImport
      parentRoute: typeof ReportsReportIdRoute
    }
  }
}

interface AlertsAlertIdRouteChildren {
  AlertsAlertIdEditRoute: typeof AlertsAlertIdEditRoute
}

const AlertsAlertIdRouteChildren: AlertsAlertIdRouteChildren = {
  AlertsAlertIdEditRoute: AlertsAlertIdEditRoute,
}

const AlertsAlertIdRouteWithChildren = AlertsAlertIdRoute._addFileChildren(
  AlertsAlertIdRouteChildren,
)

interface AlertsRouteChildren {
  AlertsAlertIdRoute: typeof AlertsAlertIdRouteWithChildren
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsAlertIdRoute: AlertsAlertIdRouteWithChildren,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

interface DashboardsDashboardIdRouteChildren {
  DashboardsDashboardIdEditRoute: typeof DashboardsDashboardIdEditRoute
}

const DashboardsDashboardIdRouteChildren: DashboardsDashboardIdRouteChildren = {
  DashboardsDashboardIdEditRoute: DashboardsDashboardIdEditRoute,
}

const DashboardsDashboardIdRouteWithChildren =
  DashboardsDashboardIdRoute._addFileChildren(
    DashboardsDashboardIdRouteChildren,
  )

interface DashboardsRouteChildren {
  DashboardsDashboardIdRoute: typeof DashboardsDashboardIdRouteWithChildren
}

const DashboardsRouteChildren: DashboardsRouteChildren = {
  DashboardsDashboardIdRoute: DashboardsDashboardIdRouteWithChildren,
}

const DashboardsRouteWithChildren = DashboardsRoute._addFileChildren(
  DashboardsRouteChildren,
)

interface DatasetsRouteChildren {
  DatasetsConnectorIdRoute: typeof DatasetsConnectorIdRoute
  DatasetsIndexRoute: typeof DatasetsIndexRoute
}

const DatasetsRouteChildren: DatasetsRouteChildren = {
  DatasetsConnectorIdRoute: DatasetsConnectorIdRoute,
  DatasetsIndexRoute: DatasetsIndexRoute,
}

const DatasetsRouteWithChildren = DatasetsRoute._addFileChildren(
  DatasetsRouteChildren,
)

interface LoginRouteChildren {
  LoginForgotRoute: typeof LoginForgotRoute
  LoginResetRoute: typeof LoginResetRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginForgotRoute: LoginForgotRoute,
  LoginResetRoute: LoginResetRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface ReportsReportIdRouteChildren {
  ReportsReportIdEditRoute: typeof ReportsReportIdEditRoute
}

const ReportsReportIdRouteChildren: ReportsReportIdRouteChildren = {
  ReportsReportIdEditRoute: ReportsReportIdEditRoute,
}

const ReportsReportIdRouteWithChildren = ReportsReportIdRoute._addFileChildren(
  ReportsReportIdRouteChildren,
)

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRouteWithChildren
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRouteWithChildren,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ApiKeysRoute: ApiKeysRoute,
  DashboardRoute: DashboardRoute,
  DashboardsRoute: DashboardsRouteWithChildren,
  DatasetsRoute: DatasetsRouteWithChildren,
  EmbedRoute: EmbedRoute,
  LoginRoute: LoginRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AdminAccessLogsRoute: AdminAccessLogsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTenantsRoute: AdminTenantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
